[package]
name = "transparentlog_core"
version = "0.1.0"
edition = "2021"

[dependencies]
rust-crypto = "0.2.36"
num = "0.4.0"
maybe-owned = "0.3.4"
thiserror = "1.0.30"
anyhow = "1.0.53"

[dev-dependencies] 
serial_test = "0.5.1"